# Generated by Django 6.1.1 on 2026-09-21 16:59

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        # The vector type only exists once the pgvector
        # extension is enabled. Fresh databases (e.g. the
        # Render PostgreSQL instance) need this before the
        # embedding column can be added.
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
