# Generated by Django 6.1.1 on 2026-09-27 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What connects through this token, for example 'Intranet portal' or 'Teams bot'.", max_length=100)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, help_text='First characters of the key, so tokens can be recognised without knowing the full secret.', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Empty means the token is valid until it is deactivated.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(help_text="The organisation this token acts within. Requests with this token see only that organisation's assistants and knowledge.", on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='core.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API token',
                'constraints': [models.UniqueConstraint(fields=('organisation', 'name'), name='unique_api_token_name_per_organisation')],
            },
        ),
    ]
