# Generated by Django 6.1.1 on 2026-09-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('core', '0002_organisationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='ai.assistant')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_access', to='core.organisationmembership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'assistant'), name='unique_assistant_access')],
            },
        ),
    ]
